name: silc-dev-requirements

channels:
  - anaconda
  - conda-forge
dependencies:
  - make
  - cmake >=3.1
  - sphinx 
  - sphinx_rtd_theme
  - sphinxcontrib-apidoc 
  - breathe
  - doxygen
  - pytest
  - xtl
  - xtensor
  - sphinx
  - doxygen
  - breathe
  - python >=3.6
  - numpy
  - xtensor-python
  - pybind11
  
  - pip
  - pip:
    - exhale