#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

( cd ahmedBody2D_snappyHexMesh && cleanCase0 && rm -rf constant )

( cd ahmedBody2D_pimpleFoam && cleanCase0 )

#------------------------------------------------------------------------------
