#!/bin/bash
cd "${0%/*}" || exit
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions
#------------------------------------------------------------------------------

# run case
runParallel pimpleFoam
touch finished.txt

#------------------------------------------------------------------------------
