#!/usr/bin/env bash

if [ -z $OFML_DRL_TORCH ]; 
then 
    echo "Torch not configured, edit variables in setup-etc, then 'source setup-etc'"
    exit 1
fi

if [ ! -d "libtorch" ]; 
then 
    wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.12.0%2Bcpu.zip && \
    unzip libtorch-cxx11-abi-shared-with-deps-1.12.0+cpu.zip
fi

wmake all src/cpp