#!/bin/bash
cd "${0%/*}" || exit
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions
#------------------------------------------------------------------------------

cleanCase
rm -rf 0 trajectory.csv finished.txt

#------------------------------------------------------------------------------
