#!/usr/bin/env bash

# Use `-with-bear` if you are compiling openfoam-ml to use it with VScode 
# https://openfoamwiki.net/index.php/HowTo_Use_OpenFOAM_with_Visual_Studio_Code
WITH_BEAR=$1

if [ -z $OF_TORCH_INCLUDE ]; 
then 
    echo "Torch not configured, edit variables in setup-torch.sh, then 'source setup-torch.sh'"
    exit 1
fi

if [ -z $OF_TORCH_LIB ]; 
then
    echo "Torch not configured, edit variables in setup-torch.sh, then 'source setup-torch.sh'"
    exit 1
fi

if [ ! -d "libtorch" ]; 
then
    if [ ! -f "libtorch-cxx11-abi-shared-with-deps-1.7.1+cpu.zip" ];
    then
        wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.7.1%2Bcpu.zip
    fi
    unzip libtorch-cxx11-abi-shared-with-deps-1.7.1+cpu.zip
fi

wmake $WITH_BEAR all application

