codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: 0%
    patch:
      default:
        target: 0%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files"
  behavior: default # update comment if already exists, otherwise post new
  require_changes: yes
  require_base: yes
  require_head: yes
